train:
  dataset_name: "Spectralis"
  path: "/home/ubuntu/armin/RetiFluidNet-main/dataset"
  image_size: 256
  in_channels: 1
  num_classes: 2 #Should include background
  image_format: '.png'
  mask_format: '_mask.png'
  seed: 100
  epochs: 1
  batch_size: 8
  buffer_size: 10000
  initial_learning_rate: 0.0002
  split: 0.8 
  classes_names: ['background', 'Retina'] #Should include background


inference:
  path: "samples"
  checkpoint: "checkpoints/model_1_epoch30.hdf5"
  save_path: "results"
  image_size: 256
  in_channels: 1
  num_classes: 2
